### ISSUE TITLE
Backbones overlapping with atoms part of 3-membered rings are incorrectly drawn

### ISSUE THREAD

**Issue by BTheDragonMaster** [SophieVromans/RAIChU#5]
![cluster_160](https://github.com/SophieVromans/RAIChU/assets/47810869/fdf986f7-7ede-49a2-b00a-98243e00c4f0)

**Comment by BTheDragonMaster** [comment]
3-membered rings not overlapping with the backbone give rise to the same problem:

![cluster_191](https://github.com/SophieVromans/RAIChU/assets/47810869/1a4a3c33-2949-464c-b7cb-47c325a5e978)

**Comment by FriederikeBiermann** [comment]
Fixed problem
